name: ntesco_smart_monitoring
description: NTESCO Smart Monitoring

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bmprogresshud: ^1.0.1
  flutter_staggered_animations: ^1.0.0
  http: ^0.13.4
  intl: ^0.17.0
  adaptive_dialog: ^1.8.3
  cupertino_icons: ^1.0.3
  ionicons: ^0.2.1  
  path_provider: ^2.0.14
  shared_preferences: ^2.0.7
  easy_localization: ^3.0.0
  cached_network_image: ^3.2.3
  url_launcher: ^6.1.10
  hexcolor: ^2.0.5 
  badges: ^3.0.3
  awesome_select: ^6.0.0
  sticky_headers: ^0.3.0+2
  flutter_slidable: ^2.0.0
  bottom_navy_bar: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_chat_ui: ^1.6.6
  timeline_tile: ^2.0.0
  grouped_list: ^5.1.2
  connectivity_plus: ^3.0.2 
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0  
  image_picker: ^0.8.7+1
  photo_view: ^0.14.0
  modal_bottom_sheet: ^2.1.2
  awesome_snackbar_content: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/language/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
