name: ntesco_smart_monitoring
description: NTESCO Smart Monitoring

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bmprogresshud: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  http: ^0.13.4
  intl: ^0.17.0
  adaptive_dialog: ^1.1.0
  cupertino_icons: ^1.0.3
  ionicons: ^0.2.1
  flutter_svg: ^0.22.0
  provider: ^6.0.0
  shared_preferences: ^2.0.7
  easy_localization: ^3.0.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.0.9
  hexcolor: ^2.0.5
  flutter_tags: ^0.4.9+1
  badges: ^2.0.3
  awesome_select: ^6.0.0
  sticky_headers: ^0.3.0+2
  flutter_slidable: ^2.0.0
  bottom_navy_bar: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_chat_ui: ^1.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/language/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
